export const FORMULARIO_PROYECTO = 'FORMULARIO_PROYECTO';
export const ERROR_FORMULARIO = 'ERROR_FORMULARIO';
export const LISTA_PROYECTOS = 'LISTA_PROYECTOS';
export const CREATE_PROYECTO = 'CREATE_PROYECTO';
export const CHANGE_PROYECTO = 'CHANGE_PROYECTO';
export const SET_SELECT_PROYECTOS = 'SET_SELECT_PROYECTOS'
export const SELECT_PROYECTOS = 'SELECT_PROYECTOS'
export const DELETE_PROYECTO = 'DELETE_PROYECTO'

//TAREAS
export const CREATE_TAREA ='CREATE_TAREA';
export const OBTENER_TAREAS ='OBTENER_TAREAS';
export const DELETE_TAREA = 'DELETE_TAREA';
export const SET_TAREA = 'SET_TAREA';
export const UPDATE_TAREA = 'UPDATE_TAREA';
export const ERROR_FORMULARIOT = 'ERROR_FORMULARIOT';

//ALERTA
export const SET_ALERTA = 'SET_ALERTA';

//AUTH
export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';

//COLABORADORES
export const ADD_COLABORADOR = 'ADD_COLABORADOR';
export const SET_SELECT_COLABORADOR = 'SET_SELECT_COLABORADOR'
export const GET_COLABORADORES = 'GET_COLABORADORES'
export const DELETE_COLABORADOR = 'DELETE_COLABORADOR'
export const GET_PROYECTOS_COLABORADOR = 'GET_PROYECTOS_COLABORADOR'
export const IS_COLABORACION = 'IS_COLABORACION'
export const ERROR_FORMULARIOC = 'ERROR_FORMULARIOC';


